projectDjango/btest/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index),
]

projectDjango/projectDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from btest import views


urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
]

projectDjango/btest/models.py
from django.db import models

class Bb(models.Model):
  title = models.CharField(max_length=50, verbose_name='Товар')
  content = models.TextField(null=True, blank=True, verbose_name='Описание')
  price = models.FloatField(null=True, blank=True, verbose_name='Цена')
  published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')
  rubric = models.ForeignKey('Rubric', null=True,   on_delete=models.PROTECT, verbose_name='Рубрика')

  
  class Meta:
    verbose_name_plural = 'Объявления'
    verbose_name = 'Объявление'
    ordering = ['-published']

class Rubric(models.Model):
  name = models.CharField(max_length=20, db_index=True,   verbose_name='Название')
  
  def __str__(self):
      return self.name


  class Meta:
    verbose_name_plural = 'Рубрики'
    verbose_name = 'Рубрика'
    ordering = ['name']

# Create your models here.

projectDjango/btest/views.py
#from django.shortcuts import render

# Create your views here.
from .models import *
from django.shortcuts import render
def index(request):
    bbs = Bb.objects.all()
    rs = Rubric.objects.all()
    return render(request, "btest/index.html", {'bbs': bbs, 'rs': rs})

projectDjango/btest/templates/btest/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta http-equiv="Content-Type" content="text/html" charset="UTF-8">
    {% load bootstrap5 %}
	{% bootstrap_javascript %}
	{% bootstrap_css %}

	<title>Главная - Доска объявлений</title>
</head>
<body>
	<h1>Объявления</h1>
	{% for bb in bbs %}
	<div>
		<h2>{{ bb.title }}</h2>
		<p>{{ bb.content }}</p>
		<p>{{ bb.published|date:"d.m.Y. H:i:s"}}</p>
		<p>Категория: {{ bb.rubric.name }}</p>
	</div>
	{% endfor %}
	<h1>Объявления по рубрикам</h1>
	{% for r in rs %}
	<div>
	    <h2>{{ r.name }}</h2>
	    {% for rbb in r.bb_set.all %}    
		<h3 >{{ rbb.title }}</h3>
		<p>{{ rbb.content }}</p>
		<p>{{ rbb.published|date:"d.m.Y. H:i:s"}}</p>
			
	    {% endfor %}
	</div>
	{% endfor %}

</body>
</html>